version: "2"

services:
  cassandra:
    image: cassandra:3.7
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  zeppelin:
    image: kryptnostic/zeppelin:0.6.1
    depends_on:
      - hazelcast-server
    ports:
      - "8080"

  spark-master:
    image: registry.krypt.int:5000/kryptnostic/spark/spark-master:0.0.0-SNAPSHOT
    depends_on:
      - hazelcast-server
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-slave:
    image: registry.krypt.int:5000/kryptnostic/spark/spark-slave:0.0.0-SNAPSHOT
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "8888:8888"
